### ISSUE TITLE
"Your Mega cloud storage is FULL"

### ISSUE THREAD

**Issue by INDIANGUY1234** [Cyberavater/Mega-Import-Bypass#2]
I used the script to save about 13TB of data on a free account....

now the account seems to be have been flagged.. with this error
""Your Mega cloud storage is FULL" upgrade account "

I am unable use even the 'get link' function... so no way to download any files..

I was wondering if u know any solution or trick to this...... is there any way to 'get the link' so  I can download the files using MegaBastard.

**Comment by retr0fnbr** [comment]
dm me on discord retr0#0999

**Comment by darlanguth** [comment]
I have de same issue. My files will be deleted in 24 days....

**Comment by Cyberavater** [comment]
> I used the script to save about 13TB of data on a free account....
> 
> now the account seems to be have been flagged.. with this error ""Your Mega cloud storage is FULL" upgrade account "
> 
> I am unable use even the 'get link' function... so no way to download any files..
> 
> I was wondering if u know any solution or trick to this...... is there any way to 'get the link' so I can download the files using MegaBastard.

I never encountered this issue, so I can't debug it. Maybe you provide me with such an example account so I can reproduce it?

**Comment by Elshan2010** [comment]
i do everything and download the extension and stuff like that but it just doesnt work. It says you need to buy to get over 20gb. It is not working as a bypass.

**Comment by FixMegScrpt** [comment]
> i do everything and download the extension and stuff like that but it just doesnt work. It says you need to buy to get over 20gb. It is not working as a bypass.

It worked, as of now **Its currently patched. The web version patched Late 9/20/23**

**Comment by Elshan2010** [comment]
> > i do everything and download the extension and stuff like that but it just doesnt work. It says you need to buy to get over 20gb. It is not working as a bypass.
> 
> It worked, as of now **Its currently patched. The web version patched Late 9/20/23**

so rn its patched and it doesnt work? the bypass dont work??

**Comment by mohamedayad1** [comment]
the script didnt work

**Comment by rahin147** [comment]
the script didnot work please help

**Comment by AnantGp** [comment]
bro the script isn't working for me.
is there anyway you can help.

**Comment by mishrasatyapriya9** [comment]
yes it is not working ,it is fake

**Comment by mishrasatyapriya9** [comment]
> > I used the script to save about 13TB of data on a free account....
> > now the account seems to be have been flagged.. with this error ""Your Mega cloud storage is FULL" upgrade account "
> > I am unable use even the 'get link' function... so no way to download any files..
> > I was wondering if u know any solution or trick to this...... is there any way to 'get the link' so I can download the files using MegaBastard.
> 
> I never encountered this issue, so I can't debug it. Maybe you provide me with such an example account so I can reproduce it?

can you plese share me the 13tb mega link
